# Exercise W6D1: Data Analysis Tools I - Pandas 

## 6.1.1 Data Wrangling and Visualizing

**Exercise 6.1.1.1** Read in the dataset "nchs_death_causes.csv" using `pandas` methods.

In [21]:
import pandas as pd
us_causes = pd.read_csv("nchs_death_causes.csv")

In [22]:
us_causes

,Year,113 Cause Name,Cause Name,State,Deaths,Age-adjusted Death Rate
0,2016,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Alabama,2755,55.5
1,2016,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Alaska,439,63.1
2,2016,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Arizona,4010,54.2
3,2016,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Arkansas,1604,51.8
4,2016,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,California,13213,32.0
...,...,...,...,...,...,...
10291,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Virginia,1035,16.9
10292,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,278,5.2
10293,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,West Virginia,345,16.4
10294,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Wisconsin,677,11.9
10295,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Wyoming,30,6.8

**Exercise 6.1.1.2** Make a `DataFrame` that is a subset of the data, containing only one cause of death and one state.

In [27]:
kidney_disease = us_causes[us_causes["Cause Name"].isin(["Kidney disease"])]
#Here we make a new dataframe
#the isin function is used to look for conditions in the list. the == is used to only look at one equal condition
kidney_disease

,Year,113 Cause Name,Cause Name,State,Deaths,Age-adjusted Death Rate
520,2016,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Alabama,1012,17.4
521,2016,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Alaska,53,10.0
522,2016,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Arizona,487,5.7
523,2016,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Arkansas,722,20.0
524,2016,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,California,3640,8.6
...,...,...,...,...,...,...
10291,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Virginia,1035,16.9
10292,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,278,5.2
10293,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,West Virginia,345,16.4
10294,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Wisconsin,677,11.9
10295,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Wyoming,30,6.8

In [35]:
#In the above I only looked at the kidney disease 
#Now I want to look at the kidney disease in Washington 

kidney_disease_Washington = kidney_disease[kidney_disease["State"].isin(["Washington"])] 

kidney_disease_Washington

#Here I printet all the cases of kidney_disease in Washington

,Year,113 Cause Name,Cause Name,State,Deaths,Age-adjusted Death Rate
568,2016,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,532,6.6
1140,2015,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,474,5.9
1712,2014,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,481,6.2
2284,2013,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,461,6.1
2856,2012,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,482,6.6
3428,2011,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,492,6.8
4000,2010,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,552,8.0
4572,2009,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,509,7.5
5144,2008,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,471,7.1
5716,2007,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,440,6.8
6288,2006,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,423,6.7
6860,2005,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,450,7.5
7432,2004,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,348,5.9
8004,2003,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,304,5.3
8576,2002,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,306,5.4
9148,2001,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,279,5.0
9720,2000,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,293,5.4
10292,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,278,5.2

**Exercise 6.1.1.3** Plot a line graph that shows the development of the death rate over time. Pay attention to whether your plot is intuitive.

In [36]:
import matplotlib.pyplot as plt

In [41]:
plt.plot(kidney_disease_Washington['Age-adjusted Death Rate'][kidney_disease_Washington['Year']

SyntaxError: unexpected EOF while parsing (<ipython-input-41-16e875c8fcf9>, line 1)

**Exercise 6.1.1.4** Make your figure self-contained and export it/save it to your machine.

**Exercise 6.1.1.5** Make a `DataFrame` that is a subset of the data, containing _two_ causes of death that might be interesting to compare for one state.

**Exercise 6.1.1.6** Create a _self-contained_ scatter plot that compares the two causes of death in the state.

**Exercise 6.1.1.7** Make a `DataFrame` that is a subset of the data, containing data for only one year and one state.

**Exercise 6.1.1.8** Create a  _self-contained_ bar graph showing the death rate across causes of death in your subset of the data.

**Exercise 6.1.1.9** Interpret your bar graph.

## _If You Have Time_ Follow Your Interests

**6.1.2.1** Think about the different data sources you have been using so far. Identify one source of data you were particularly interested in, get the data, think about what might be interesting to explore visually and plot it. Remember that there is an entire [Dataverse](https://dataverse.harvard.edu/) out there that you can draw on, which you can now easily import using the `pandas` functionality.